/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `Mouvement`;

CREATE TABLE `Mouvement` (
  `ID` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `ID_user` BIGINT UNSIGNED NOT NULL,
  `Timestamp` BIGINT UNSIGNED NOT NULL,
  `type` TEXT NOT NULL,
  `application` TEXT NOT NULL)
 ENGINE=InnoDB;

