/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `Mouvement`;

CREATE TABLE `Mouvement` (
  `idMove` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `idUser` INT NOT NULL,
  `type` TEXT NOT NULL,
  `application` TEXT NOT NULL)
 ENGINE=InnoDB;

