// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef MOUVEMENT_ODB_HXX
#define MOUVEMENT_ODB_HXX

#include <odb/version.hxx>

#if (ODB_VERSION != 20300UL)
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "mouvement.h"

#include <memory>
#include <cstddef>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/no-op-cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // Mouvement
  //
  template <>
  struct class_traits< ::Mouvement >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::Mouvement >
  {
    public:
    typedef ::Mouvement object_type;
    typedef ::Mouvement* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef long unsigned int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/mysql/version.hxx>
#include <odb/mysql/forward.hxx>
#include <odb/mysql/binding.hxx>
#include <odb/mysql/mysql-types.hxx>
#include <odb/mysql/query.hxx>

namespace odb
{
  // Mouvement
  //
  template <typename A>
  struct query_columns< ::Mouvement, id_mysql, A >
  {
    // ID
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long unsigned int,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    ID_type_;

    static const ID_type_ ID;

    // ID_user
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long unsigned int,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    ID_user_type_;

    static const ID_user_type_ ID_user;

    // Timestamp
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long unsigned int,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    Timestamp_type_;

    static const Timestamp_type_ Timestamp;

    // type
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    type_type_;

    static const type_type_ type;

    // application
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    application_type_;

    static const application_type_ application;
  };

  template <typename A>
  const typename query_columns< ::Mouvement, id_mysql, A >::ID_type_
  query_columns< ::Mouvement, id_mysql, A >::
  ID (A::table_name, "`ID`", 0);

  template <typename A>
  const typename query_columns< ::Mouvement, id_mysql, A >::ID_user_type_
  query_columns< ::Mouvement, id_mysql, A >::
  ID_user (A::table_name, "`ID_user`", 0);

  template <typename A>
  const typename query_columns< ::Mouvement, id_mysql, A >::Timestamp_type_
  query_columns< ::Mouvement, id_mysql, A >::
  Timestamp (A::table_name, "`Timestamp`", 0);

  template <typename A>
  const typename query_columns< ::Mouvement, id_mysql, A >::type_type_
  query_columns< ::Mouvement, id_mysql, A >::
  type (A::table_name, "`type`", 0);

  template <typename A>
  const typename query_columns< ::Mouvement, id_mysql, A >::application_type_
  query_columns< ::Mouvement, id_mysql, A >::
  application (A::table_name, "`application`", 0);

  template <typename A>
  struct pointer_query_columns< ::Mouvement, id_mysql, A >:
    query_columns< ::Mouvement, id_mysql, A >
  {
  };

  template <>
  class access::object_traits_impl< ::Mouvement, id_mysql >:
    public access::object_traits< ::Mouvement >
  {
    public:
    struct id_image_type
    {
      unsigned long long id_value;
      my_bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // ID
      //
      unsigned long long ID_value;
      my_bool ID_null;

      // ID_user
      //
      unsigned long long ID_user_value;
      my_bool ID_user_null;

      // Timestamp
      //
      unsigned long long Timestamp_value;
      my_bool Timestamp_null;

      // type
      //
      details::buffer type_value;
      unsigned long type_size;
      my_bool type_null;

      // application
      //
      details::buffer application_value;
      unsigned long application_size;
      my_bool application_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          my_bool*);

    static void
    bind (MYSQL_BIND*,
          image_type&,
          mysql::statement_kind);

    static void
    bind (MYSQL_BIND*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          mysql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef mysql::object_statements<object_type> statements_type;

    typedef mysql::query_base query_base_type;

    static const std::size_t column_count = 5UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::Mouvement, id_common >:
    public access::object_traits_impl< ::Mouvement, id_mysql >
  {
  };

  // Mouvement
  //
}

#include "mouvement-odb.ixx"

#include <odb/post.hxx>

#endif // MOUVEMENT_ODB_HXX
