/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `Point`;

CREATE TABLE `Point` (
  `ID` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `ID_mouvement` BIGINT UNSIGNED NOT NULL,
  `X` INT NOT NULL,
  `Y` INT NOT NULL,
  `X_relatif` DOUBLE NOT NULL,
  `Y_relatif` DOUBLE NOT NULL)
 ENGINE=InnoDB;

