/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `Point`;

CREATE TABLE `Point` (
  `idPoint` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `idMove` INT NOT NULL,
  `timestamps` DOUBLE NOT NULL,
  `X` DOUBLE NOT NULL,
  `Y` DOUBLE NOT NULL,
  `relatifX` DOUBLE NOT NULL,
  `relatifY` DOUBLE NOT NULL)
 ENGINE=InnoDB;

