// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef POINT_ODB_HXX
#define POINT_ODB_HXX

#include <odb/version.hxx>

#if (ODB_VERSION != 20300UL)
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "point.h"

#include <memory>
#include <cstddef>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/no-op-cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // Point
  //
  template <>
  struct class_traits< ::Point >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::Point >
  {
    public:
    typedef ::Point object_type;
    typedef ::Point* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef long unsigned int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/mysql/version.hxx>
#include <odb/mysql/forward.hxx>
#include <odb/mysql/binding.hxx>
#include <odb/mysql/mysql-types.hxx>
#include <odb/mysql/query.hxx>

namespace odb
{
  // Point
  //
  template <typename A>
  struct query_columns< ::Point, id_mysql, A >
  {
    // ID
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long unsigned int,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    ID_type_;

    static const ID_type_ ID;

    // ID_mouvement
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long unsigned int,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    ID_mouvement_type_;

    static const ID_mouvement_type_ ID_mouvement;

    // X
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        int,
        mysql::id_long >::query_type,
      mysql::id_long >
    X_type_;

    static const X_type_ X;

    // Y
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        int,
        mysql::id_long >::query_type,
      mysql::id_long >
    Y_type_;

    static const Y_type_ Y;

    // X_relatif
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        double,
        mysql::id_double >::query_type,
      mysql::id_double >
    X_relatif_type_;

    static const X_relatif_type_ X_relatif;

    // Y_relatif
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        double,
        mysql::id_double >::query_type,
      mysql::id_double >
    Y_relatif_type_;

    static const Y_relatif_type_ Y_relatif;
  };

  template <typename A>
  const typename query_columns< ::Point, id_mysql, A >::ID_type_
  query_columns< ::Point, id_mysql, A >::
  ID (A::table_name, "`ID`", 0);

  template <typename A>
  const typename query_columns< ::Point, id_mysql, A >::ID_mouvement_type_
  query_columns< ::Point, id_mysql, A >::
  ID_mouvement (A::table_name, "`ID_mouvement`", 0);

  template <typename A>
  const typename query_columns< ::Point, id_mysql, A >::X_type_
  query_columns< ::Point, id_mysql, A >::
  X (A::table_name, "`X`", 0);

  template <typename A>
  const typename query_columns< ::Point, id_mysql, A >::Y_type_
  query_columns< ::Point, id_mysql, A >::
  Y (A::table_name, "`Y`", 0);

  template <typename A>
  const typename query_columns< ::Point, id_mysql, A >::X_relatif_type_
  query_columns< ::Point, id_mysql, A >::
  X_relatif (A::table_name, "`X_relatif`", 0);

  template <typename A>
  const typename query_columns< ::Point, id_mysql, A >::Y_relatif_type_
  query_columns< ::Point, id_mysql, A >::
  Y_relatif (A::table_name, "`Y_relatif`", 0);

  template <typename A>
  struct pointer_query_columns< ::Point, id_mysql, A >:
    query_columns< ::Point, id_mysql, A >
  {
  };

  template <>
  class access::object_traits_impl< ::Point, id_mysql >:
    public access::object_traits< ::Point >
  {
    public:
    struct id_image_type
    {
      unsigned long long id_value;
      my_bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // ID
      //
      unsigned long long ID_value;
      my_bool ID_null;

      // ID_mouvement
      //
      unsigned long long ID_mouvement_value;
      my_bool ID_mouvement_null;

      // X
      //
      int X_value;
      my_bool X_null;

      // Y
      //
      int Y_value;
      my_bool Y_null;

      // X_relatif
      //
      double X_relatif_value;
      my_bool X_relatif_null;

      // Y_relatif
      //
      double Y_relatif_value;
      my_bool Y_relatif_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          my_bool*);

    static void
    bind (MYSQL_BIND*,
          image_type&,
          mysql::statement_kind);

    static void
    bind (MYSQL_BIND*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          mysql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef mysql::object_statements<object_type> statements_type;

    typedef mysql::query_base query_base_type;

    static const std::size_t column_count = 6UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::Point, id_common >:
    public access::object_traits_impl< ::Point, id_mysql >
  {
  };

  // Point
  //
}

#include "point-odb.ixx"

#include <odb/post.hxx>

#endif // POINT_ODB_HXX
