/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `Utilisateur`;

CREATE TABLE `Utilisateur` (
  `id` INT NOT NULL PRIMARY KEY,
  `type` TEXT NOT NULL,
  `marqueMachine` TEXT NOT NULL)
 ENGINE=InnoDB;

